// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: pack.proto

package msgpack

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	payload "minesweeper/test/payload"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MsgPack struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Type   []byte                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Target string                 `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*MsgPack_GameInitPayload
	//	*MsgPack_ClickPayload
	//	*MsgPack_MapChangePayload
	Payload       isMsgPack_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MsgPack) Reset() {
	*x = MsgPack{}
	mi := &file_pack_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MsgPack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgPack) ProtoMessage() {}

func (x *MsgPack) ProtoReflect() protoreflect.Message {
	mi := &file_pack_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgPack.ProtoReflect.Descriptor instead.
func (*MsgPack) Descriptor() ([]byte, []int) {
	return file_pack_proto_rawDescGZIP(), []int{0}
}

func (x *MsgPack) GetType() []byte {
	if x != nil {
		return x.Type
	}
	return nil
}

func (x *MsgPack) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *MsgPack) GetPayload() isMsgPack_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *MsgPack) GetGameInitPayload() *payload.GameInitPayload {
	if x != nil {
		if x, ok := x.Payload.(*MsgPack_GameInitPayload); ok {
			return x.GameInitPayload
		}
	}
	return nil
}

func (x *MsgPack) GetClickPayload() *payload.ClickPayload {
	if x != nil {
		if x, ok := x.Payload.(*MsgPack_ClickPayload); ok {
			return x.ClickPayload
		}
	}
	return nil
}

func (x *MsgPack) GetMapChangePayload() *payload.MapChangePayload {
	if x != nil {
		if x, ok := x.Payload.(*MsgPack_MapChangePayload); ok {
			return x.MapChangePayload
		}
	}
	return nil
}

type isMsgPack_Payload interface {
	isMsgPack_Payload()
}

type MsgPack_GameInitPayload struct {
	GameInitPayload *payload.GameInitPayload `protobuf:"bytes,3,opt,name=gameInitPayload,proto3,oneof"`
}

type MsgPack_ClickPayload struct {
	ClickPayload *payload.ClickPayload `protobuf:"bytes,4,opt,name=clickPayload,proto3,oneof"`
}

type MsgPack_MapChangePayload struct {
	MapChangePayload *payload.MapChangePayload `protobuf:"bytes,5,opt,name=mapChangePayload,proto3,oneof"`
}

func (*MsgPack_GameInitPayload) isMsgPack_Payload() {}

func (*MsgPack_ClickPayload) isMsgPack_Payload() {}

func (*MsgPack_MapChangePayload) isMsgPack_Payload() {}

var File_pack_proto protoreflect.FileDescriptor

const file_pack_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"pack.proto\x12\amsgpack\x1a\x15payload/payload.proto\"\x8c\x02\n" +
	"\aMsgPack\x12\x12\n" +
	"\x04type\x18\x01 \x01(\fR\x04type\x12\x16\n" +
	"\x06target\x18\x02 \x01(\tR\x06target\x12D\n" +
	"\x0fgameInitPayload\x18\x03 \x01(\v2\x18.payload.gameInitPayloadH\x00R\x0fgameInitPayload\x12;\n" +
	"\fclickPayload\x18\x04 \x01(\v2\x15.payload.clickPayloadH\x00R\fclickPayload\x12G\n" +
	"\x10mapChangePayload\x18\x05 \x01(\v2\x19.payload.mapChangePayloadH\x00R\x10mapChangePayloadB\t\n" +
	"\apayloadB\x1aZ\x18minesweeper/test;msgpackb\x06proto3"

var (
	file_pack_proto_rawDescOnce sync.Once
	file_pack_proto_rawDescData []byte
)

func file_pack_proto_rawDescGZIP() []byte {
	file_pack_proto_rawDescOnce.Do(func() {
		file_pack_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pack_proto_rawDesc), len(file_pack_proto_rawDesc)))
	})
	return file_pack_proto_rawDescData
}

var file_pack_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pack_proto_goTypes = []any{
	(*MsgPack)(nil),                  // 0: msgpack.MsgPack
	(*payload.GameInitPayload)(nil),  // 1: payload.gameInitPayload
	(*payload.ClickPayload)(nil),     // 2: payload.clickPayload
	(*payload.MapChangePayload)(nil), // 3: payload.mapChangePayload
}
var file_pack_proto_depIdxs = []int32{
	1, // 0: msgpack.MsgPack.gameInitPayload:type_name -> payload.gameInitPayload
	2, // 1: msgpack.MsgPack.clickPayload:type_name -> payload.clickPayload
	3, // 2: msgpack.MsgPack.mapChangePayload:type_name -> payload.mapChangePayload
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_pack_proto_init() }
func file_pack_proto_init() {
	if File_pack_proto != nil {
		return
	}
	file_pack_proto_msgTypes[0].OneofWrappers = []any{
		(*MsgPack_GameInitPayload)(nil),
		(*MsgPack_ClickPayload)(nil),
		(*MsgPack_MapChangePayload)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pack_proto_rawDesc), len(file_pack_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pack_proto_goTypes,
		DependencyIndexes: file_pack_proto_depIdxs,
		MessageInfos:      file_pack_proto_msgTypes,
	}.Build()
	File_pack_proto = out.File
	file_pack_proto_goTypes = nil
	file_pack_proto_depIdxs = nil
}
