// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: payload/payload.proto

package payload

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GameInitPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	MineNum       int32                  `protobuf:"varint,3,opt,name=mineNum,proto3" json:"mineNum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameInitPayload) Reset() {
	*x = GameInitPayload{}
	mi := &file_payload_payload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameInitPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameInitPayload) ProtoMessage() {}

func (x *GameInitPayload) ProtoReflect() protoreflect.Message {
	mi := &file_payload_payload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameInitPayload.ProtoReflect.Descriptor instead.
func (*GameInitPayload) Descriptor() ([]byte, []int) {
	return file_payload_payload_proto_rawDescGZIP(), []int{0}
}

func (x *GameInitPayload) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *GameInitPayload) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *GameInitPayload) GetMineNum() int32 {
	if x != nil {
		return x.MineNum
	}
	return 0
}

type ClickPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	IsLeftClick   bool                   `protobuf:"varint,3,opt,name=isLeftClick,proto3" json:"isLeftClick,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClickPayload) Reset() {
	*x = ClickPayload{}
	mi := &file_payload_payload_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClickPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClickPayload) ProtoMessage() {}

func (x *ClickPayload) ProtoReflect() protoreflect.Message {
	mi := &file_payload_payload_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClickPayload.ProtoReflect.Descriptor instead.
func (*ClickPayload) Descriptor() ([]byte, []int) {
	return file_payload_payload_proto_rawDescGZIP(), []int{1}
}

func (x *ClickPayload) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ClickPayload) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *ClickPayload) GetIsLeftClick() bool {
	if x != nil {
		return x.IsLeftClick
	}
	return false
}

type MapChangeEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Value         int32                  `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapChangeEvent) Reset() {
	*x = MapChangeEvent{}
	mi := &file_payload_payload_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapChangeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapChangeEvent) ProtoMessage() {}

func (x *MapChangeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_payload_payload_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapChangeEvent.ProtoReflect.Descriptor instead.
func (*MapChangeEvent) Descriptor() ([]byte, []int) {
	return file_payload_payload_proto_rawDescGZIP(), []int{2}
}

func (x *MapChangeEvent) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *MapChangeEvent) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *MapChangeEvent) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type MapChangePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*MapChangeEvent      `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapChangePayload) Reset() {
	*x = MapChangePayload{}
	mi := &file_payload_payload_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapChangePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapChangePayload) ProtoMessage() {}

func (x *MapChangePayload) ProtoReflect() protoreflect.Message {
	mi := &file_payload_payload_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapChangePayload.ProtoReflect.Descriptor instead.
func (*MapChangePayload) Descriptor() ([]byte, []int) {
	return file_payload_payload_proto_rawDescGZIP(), []int{3}
}

func (x *MapChangePayload) GetEvents() []*MapChangeEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_payload_payload_proto protoreflect.FileDescriptor

const file_payload_payload_proto_rawDesc = "" +
	"\n" +
	"\x15payload/payload.proto\x12\apayload\"G\n" +
	"\x0fgameInitPayload\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\x12\x18\n" +
	"\amineNum\x18\x03 \x01(\x05R\amineNum\"L\n" +
	"\fclickPayload\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\x12 \n" +
	"\visLeftClick\x18\x03 \x01(\bR\visLeftClick\"B\n" +
	"\x0emapChangeEvent\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\x12\x14\n" +
	"\x05value\x18\x03 \x01(\x05R\x05value\"C\n" +
	"\x10mapChangePayload\x12/\n" +
	"\x06events\x18\x01 \x03(\v2\x17.payload.mapChangeEventR\x06eventsB\"Z minesweeper/test/payload;payloadb\x06proto3"

var (
	file_payload_payload_proto_rawDescOnce sync.Once
	file_payload_payload_proto_rawDescData []byte
)

func file_payload_payload_proto_rawDescGZIP() []byte {
	file_payload_payload_proto_rawDescOnce.Do(func() {
		file_payload_payload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_payload_payload_proto_rawDesc), len(file_payload_payload_proto_rawDesc)))
	})
	return file_payload_payload_proto_rawDescData
}

var file_payload_payload_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_payload_payload_proto_goTypes = []any{
	(*GameInitPayload)(nil),  // 0: payload.gameInitPayload
	(*ClickPayload)(nil),     // 1: payload.clickPayload
	(*MapChangeEvent)(nil),   // 2: payload.mapChangeEvent
	(*MapChangePayload)(nil), // 3: payload.mapChangePayload
}
var file_payload_payload_proto_depIdxs = []int32{
	2, // 0: payload.mapChangePayload.events:type_name -> payload.mapChangeEvent
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_payload_payload_proto_init() }
func file_payload_payload_proto_init() {
	if File_payload_payload_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payload_payload_proto_rawDesc), len(file_payload_payload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_payload_payload_proto_goTypes,
		DependencyIndexes: file_payload_payload_proto_depIdxs,
		MessageInfos:      file_payload_payload_proto_msgTypes,
	}.Build()
	File_payload_payload_proto = out.File
	file_payload_payload_proto_goTypes = nil
	file_payload_payload_proto_depIdxs = nil
}
